### ISSUE TITLE
Rancher isn't even using longhorn... but AWX probably should

### ISSUE THREAD

**Issue by PC-Admin** [PC-Admin/ehi-bootstrap-playbook#4]
this command is fine to install Rancher:

`$ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher.estuary.tech --set ingress.tls.source=secret --set bootstrapPassword=REDACTED --create-namespace --set replicas=3`

We don't actually need to use longhorn storage for it, the only think we'd want it for IMO is doing dumps of AWX's database routinely as a backup/recovery method.

**Comment by Zorlin** [comment]
> the only think we'd want it for IMO is doing dumps of AWX's database routinely as a backup/recovery method.

Longhorn is not a valid place to store backups - look at S3 or MooseFS instead.

**Comment by PC-Admin** [comment]
Wasn't thinking about storing them there, just having is as a temporary space that AWX can write to for it's dumps. (which would then me moved elsewhere)

Isn't Longhorn supposed to be what actually makes this storage available to AWX? How could I directly mount S3 or MooseFS to it instead?

**Comment by PC-Admin** [comment]
If this really no use for it when I guess we'll just tear the longhorn section out and move on.

**Comment by Zorlin** [comment]
No, I'm not saying there's no use for it. longhorn is used for storing AWX data...

**Comment by Zorlin** [comment]
It's just that Longhorn is not meant to be a place to store backups. It's simply not that level of trustworthy.

**Comment by PC-Admin** [comment]
Turns out Longhorn becomes the standard storage class for RKE2 when installed, so AWX is already using it.

As for persistence, charts, playbooks, variables are best defined in Git. The DB of the prod AWX setup will eventually be located in our Postgresql cluster where we can do backups from.
